<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Library</OutputType>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Dapper" Version="2.1.79" />
	<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
	<PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PilotUtiltyApi.Domain\PilotUtilityApi.Domain.csproj" />
    <ProjectReference Include="..\PilotUtiltyApi.Shared\PilotUtilityApi.Shared.csproj" />
  </ItemGroup>

</Project>
