<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Library</OutputType>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
	<PackageReference Include="Microsoft.AspNetCore.Mvc.ApiExplorer" Version="2.3.11" />
	<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
	<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	<PackageReference Include="Npgsql.OpenTelemetry" Version="10.0.3" />
	<PackageReference Include="Scalar.AspNetCore" Version="2.16.18" />
	<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
	<PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
	<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
	<PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
	<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
	<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	<PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />
	<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Constants\" />
  </ItemGroup>

</Project>
