<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Library</OutputType>
	<IsPackable>false</IsPackable>
	<IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="coverlet.collector">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.Extensions.Logging" />
	<PackageReference Include="Moq" />
	<PackageReference Include="Moq.Dapper" />
	<PackageReference Include="NUnit" />
	<PackageReference Include="NUnit.Analyzers" >
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PilotUtiltyApi.Shared\PilotUtilityApi.Shared.csproj" />
  </ItemGroup>
</Project>
